export const TOGGLE_MAIN_NAV_VIEW = 'TOGGLE_MAIN_NAV_VIEW'
export const TOGGLE_USER_NAV_VIEW = 'TOGGLE_USER_NAV_VIEW'
export const TOGGLE_LANG_NAV_VIEW = 'TOGGLE_LANG_NAV_VIEW'
export const HIDE_ALL_NAVS = 'HIDE_ALL_NAVS'