

. devops + azure pipelines + data factory + databricks + python + spark + hdfs + OUTPUT_DEST {
	. Azure Data Factory {
P:\local\hcl-percipio\19-7-2025-a
	CR-AzureDataScientistAssociateAzureDataFactory
|   CR-DataEngineeringOnMicrosoftAzureDataFactory

P:\local\hcl-percipio\19-7-2025-b
	CR-DataEngineeringOnMicrosoftAzureDataProcessMonitoring
	CR-AzureDataScientistAssociateAzureDataPlatformServices
	CR-AzureDataFundamentalsAzureDataIngestionProcessing
	CR-AzureDataFundamentalsModernDataWarehousing
	CR-DataEngineeringOnMicrosoftAzureDataLakeStorage
	
	}
	. Azure Databricks {

+---19-7-2025-b
|   +---CR-AzureDatabricksDataPipelines
|   +---CR-DataEngineeringOnMicrosoftAzureDatabrickProcessing
|   +---CR-DataEngineeringOnMicrosoftAzureDatabricks
|   +---CR-HyperparameterTuningWithHyperoptOnDatabricks
|   +---CR-HyperparameterTuningWithRayTuneOnDatabricks
|   +---CR-DataScienceSolutionOnAzureDataSolutionOptimization
|   +---CR-DataEngineeringOnMicrosoftAzureDataLakeStorage

	}
	. devops regarding azure pipelines {
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS

	in-progress: LIN - AzureDevOps EngiExpert AZ-400 CertPrep : ***
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\AzureDevOps EngiExpert AZ-400 CertPrep
	Azure DevOps: Continuous Delivery with YAML Pipelines : ***
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Azure-DevOps-Continuous-Delivery-with-YAML-Pipelines

. others {
	Developing CI/CD Solutions with Azure DevOps : *
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Developing-CI_CD-Solutions-with-Azure-DevOps

	Continuous-Delivery-with-Azure-DevOps
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Continuous-Delivery-with-Azure-DevOps
	Azure-for-DevOps-Implementing-Development-Processes
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Azure-for-DevOps-Implementing-Development-Processes

	Integrating-Azure-DevOps-with-GitHub
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Integrating-Azure-DevOps-with-GitHub

	Exam Tips AZ 400 Designing_Implementing Microsoft DevOps Solutions: n
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Exam-Tips-AZ-400-Designing_Implementing-Microsoft-DevOps-Solutions
	Done: Learning-Azure-DevOps
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Learning-Azure-DevOps
	Azure DevOps for Beginners
}

	}
	
	. ds {
DATA-SCIENCE	CORE		Data Science Foundations Data Engineering	2
	}
}
. spark {
	
}
. python + hdfs + OUTPUT_DEST {
	
}

. online portals {
	. py {
https://www.w3schools.com/python/default.asp
https://www.tutorialsteacher.com/python
https://www.tutorialspoint.com/python/python_interview_questions.htm
	}
}