. devops {
}
. az pipeline {}
. az devops {
	.lin {
	P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS
	Azure DevOps for Beginners

	Developing CI/CD Solutions with Azure DevOps: y
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Developing-CI_CD-Solutions-with-Azure-DevOps
	Azure DevOps: Continuous Delivery with YAML Pipelines: y
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Azure-DevOps-Continuous-Delivery-with-YAML-Pipelines
	Azure Data Factory

	LIN - AzureDevOps EngiExpert AZ-400 CertPrep
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\AzureDevOps EngiExpert AZ-400 CertPrep
	Exam Tips AZ 400 Designing_Implementing Microsoft DevOps Solutions: y
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Exam-Tips-AZ-400-Designing_Implementing-Microsoft-DevOps-Solutions
	Azure-for-DevOps-Implementing-Development-Processes
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Azure-for-DevOps-Implementing-Development-Processes
	Continuous-Delivery-with-Azure-DevOps
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Continuous-Delivery-with-Azure-DevOps
	Integrating-Azure-DevOps-with-GitHub
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Integrating-Azure-DevOps-with-GitHub
	Learning-Azure-DevOps
P:\local\2-TECH-BACK\9-DEPLOY\41-AZURE\DEVOPS\Learning-Azure-DevOps
	}
}
. data factory {
	
}
. data bricks {
	
}
. spark {
	
}
. python + hdfs + OUTPUT_DEST {
	
}

. online portals {
	. py {
https://www.w3schools.com/python/default.asp
https://www.tutorialsteacher.com/python
https://www.tutorialspoint.com/python/python_interview_questions.htm
	}
}